version: '3.5'
services:
  web:
    build: ./
    command: python app.py
    restart: always
    depends_on:
      - database
    volumes:
      - .:/usr/src/app
    ports:
      - 5001:5000
    env_file:
      - ./.env

  database:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file: .env
    ports:
      - 7000:5432
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume: