version: '3.5'
services:
  web:
    build: ./
    command: python app.py
    restart: always
    depends_on:
      - database
    volumes:
      - .:/usr/src/app
    ports:
      - 5001:5000
    env_file:
      - ./.env

  database:
    container_name: postgres
    image: postgres:latest
    restart: always
    user: postgres
    env_file: .env
    ports:
      - 7000:5432
    volumes:
      - db_volume:/var/lib/postgresql
      - ./postgres-data:/var/lib/postgresql/data
      - ./document_test.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  db_volume: